# Docker Compose
# spring:
#   datasource:
#     url: jdbc:mysql://mysql:3306/Tika
#     username: root
#     password: root
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     type: com.alibaba.druid.pool.DruidDataSource

#   data:
#     redis:
#       host: redis
#       port: 6379
#       password: redis
#       database: 0


# Selfhosted
spring:
  datasource:
    url: jdbc:mysql://119.29.147.37:3306/Tika
    username: root
    password: mysql_6kJfZ5
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  data:
    redis:
      host: 119.29.147.37
      port: 6379
      password: redis_cAFXar
      database: 0