spring:
  datasource:
    url: jdbc:mysql://mysql:3306/Tika
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  data:
    redis:
      host: redis
      port: 6379
      password: redis
      database: 0