server:
  port: 8080

spring:
  profiles:
    active: prod

  datasource:
    driver-class-name: ${spring.datasource.type}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    type: ${spring.datasource.type}

  data:
    redis:
      host: ${spring.data.redis.host}
      password: ${spring.data.redis.password}
      port: ${spring.data.redis.port}
      database: ${spring.data.redis.database}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.soopy.echo.entity
  configuration:
    map-underscore-to-camel-case: true


tika:
  jwt:
    # 设置签名加密时使用的密钥
    secret-key: L1nSn0w-114514-YYDS-LinSnow-666-TIKA
    # 设置jwt过期时间
    ttl: 720000000
    # 设置前端传递过来的令牌名称
    token-name: token
