services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Tika
    networks:
      - tika-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: redis
    restart: always
    command: redis-server --requirepass redis
    networks:
      - tika-network

  backend:
    build: 
      context: ./Tika-Backend
      dockerfile: Dockerfile
    container_name: tika-backend
    networks:
      - tika-network
    depends_on:
      - mysql
      - redis

  frontend:
    build:
      context: ./Tika-Web
      dockerfile: Dockerfile
    container_name: tika-frontend
    networks:
      - tika-network
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: tika-nginx
    restart: always
    ports:
      - "4088:80"
    networks:
      - tika-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

networks:
  tika-network:
    driver: bridge